export const UI_COPY = {
  metadataTitle: "图片生成器",
  metadataDescription: "使用 GPT Image 生成图片",
  brand: "图片工具",
  eyebrow: "生成设置",
  heroTitle: "图片生成",
  heroDescription: "输入提示词并生成图片。",
  apiKeyLabel: "API Key",
  apiKeyPlaceholder: "输入你的 OpenAI API Key",
  apiKeyHint: "仅保存在当前浏览器标签页，关闭后自动清除。",
  apiKeyRequired: "请输入 API Key。",
  apiBaseURLLabel: "API 地址（可选）",
  apiBaseURLPlaceholder: "https://api.openai.com/v1",
  apiBaseURLHint: "留空时使用 OpenAI 官方接口。",
  promptLabel: "提示词",
  promptPlaceholder: "例如：一张电影感产品照，透明柑橘香水瓶放在黑色大理石上，边缘光，杂志风，高细节",
  promptHint: "建议写清主体、场景和风格。",
  promptTooShort: "提示词太短，请再补充一点。",
  promptRequired: "请输入至少 3 个字符的提示词。",
  referenceImageLabel: "参考图",
  referenceImageHint: "点击上传、拖拽或粘贴图片",
  referenceImageSelectedHint: "将按参考图修改",
  referenceImageClear: "清除图片",
  referenceImageInvalidType: "图片格式不支持，请上传 PNG、JPEG、JPG 或 WebP。",
  referenceImageInvalidSize: "图片不能超过 50 MB。",
  referenceImageAlt: "参考图预览",
  referenceImageChangeAriaLabel: "更换参考图",
  outputGroup: "输出设置",
  sizeLabel: "尺寸",
  countLabel: "图片数量",
  renderingGroup: "渲染设置",
  qualityLabel: "质量",
  styleLabel: "风格",
  generateIdle: "生成图片",
  generateLoading: "正在生成…",
  jobResumeNotice: "正在恢复上一次生成任务，请稍候。",
  jobRunningStatus: "任务运行中",
  jobPollingNotice: "图片正在生成中，完成后会自动显示。",
  jobStartFailed: "启动生成任务失败，请稍后重试。",
  jobPollingFailed: "暂时无法获取生成进度，请重新提交任务。",
  previewEyebrowIdle: "预览",
  previewEyebrowLoading: "生成中",
  previewTitleIdle: "准备生成",
  previewTitleLoading: "正在渲染图片",
  previewTitleReady: "生成结果",
  previewStatusEmpty: "暂无图片",
  previewStatusLoading: "生成中",
  previewStatusReadySingular: "1 张图片已生成",
  previewStatusReadyPlural: "{count} 张图片已生成",
  emptyState: "暂无图片。生成结果会显示在这里。",
  noImagesReturned: "没有返回图片。请尝试写得更具体一点。",
  generationFailed: "图片生成失败，请稍后重试。",
  unknownGenerationError: "生成图片时出错。",
  downloadPng: "下载 PNG",
  editImage: "裁剪/压缩",
  editorHeading: "裁剪/压缩",
  editorClose: "关闭",
  editorResetCrop: "重置裁剪",
  editorMatchReferenceRatio: "按参考图比例",
  editorFormat: "格式",
  editorQuality: "质量",
  editorOutputSize: "输出尺寸",
  editorOutputCrop: "裁剪尺寸",
  editorOutputReference: "参考图尺寸",
  editorOutputCustom: "自定义",
  editorCropX: "裁剪 X",
  editorCropY: "裁剪 Y",
  editorCropWidth: "裁剪宽度",
  editorCropHeight: "裁剪高度",
  editorWidth: "宽度",
  editorHeight: "高度",
  editorFit: "适配方式",
  editorFitContain: "完整保留",
  editorFitCover: "铺满裁剪",
  editorApply: "应用导出",
  editorExportFailed: "导出图片失败，请重试。",
  editorSourceAlt: "待编辑图片",
  editorResizeHandleLabel: "调整裁剪区域",
  historyHeading: "历史记录",
  historySavedCount: "已保存 {count}/50",
  historyLocalNotice: "历史记录仅保存在本机浏览器。",
  historyEmpty: "暂无历史记录。",
  historyModeGenerate: "文生图",
  historyModeEdit: "图生图",
  historyView: "查看",
  historyDelete: "删除",
  historyClearAll: "清空全部",
  historyImageAlt: "历史记录缩略图",
  historyLoadFailed: "读取历史记录失败。",
  historySaveFailed: "保存历史记录失败。",
  historyDeleteFailed: "删除历史记录失败。",
  historyClearFailed: "清空历史记录失败。",
  controlsAriaLabel: "图片生成设置",
  previewAriaLabel: "生成图片预览",
  generatedImageAlt: "生成图片 {index}",
} as const;

const OPTION_LABELS: Record<string, string> = {
  auto: "自动",
  low: "低质量",
  medium: "中等质量",
  high: "高质量",
  natural: "自然",
  vivid: "鲜明",
};

export function optionLabel(value: string | number) {
  const text = String(value);
  return OPTION_LABELS[text] || text.replace("x", " × ");
}

export function imageCountLabel(count: number) {
  return `${count} 张图片`;
}

export function previewReadyStatus(count: number) {
  return count === 1
    ? UI_COPY.previewStatusReadySingular
    : UI_COPY.previewStatusReadyPlural.replace("{count}", String(count));
}
